### ISSUE TITLE
Search Scroll > Search Bug

### ISSUE THREAD

**Issue by colinchoix** [CMPUT301W18T05/Taskzilla#92]

**Comment by colinchoix** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.cmput301w18t05.taskzilla, PID: 25642
                  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getTop()' on a null object reference
                      at com.cmput301w18t05.taskzilla.fragment.SearchFragment$3.onScroll(SearchFragment.java:136)
                      at android.widget.AbsListView.invokeOnItemScrollListener(AbsListView.java:2213)
                      at android.widget.ListView.layoutChildren(ListView.java:1744)
                      at android.widget.AbsListView.onLayout(AbsListView.java:3008)
                      at android.view.View.layout(View.java:18804)
                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                      at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1197)
                      at android.view.View.layout(View.java:18804)
                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                      at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1767)
                      at android.view.View.layout(View.java:18804)
                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                      at android.view.View.layout(View.java:18804)
                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:18804)
                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                      at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
                      at android.view.View.layout(View.java:18804)
                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:18804)
                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                      at android.view.View.layout(View.java:18804)
                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:887)
                      at android.view.View.layout(View.java:18804)
                      at android.view.ViewGroup.layout(ViewGroup.java:5951)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2655)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2371)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7098)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                      at android.view.Choreographer.doFrame(Choreographer.java:638)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6682)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
